---
- hosts: localhost
  vars:
    tenantid: "tno85405"
    apitoken: "9Tgt4MNUSPe6qNdKnvXJA"
    dt_app: "front-end"
    dt_env: "dev"
    dteventapiurl: "https://{{tenantid}}.live.dynatrace.com/api/v1/events/?Api-Token={{apitoken}}"
    jenkins_user: "admin"
    jenkins_password: "admin"
    jenkins_url: "http://35.239.237.67/job/k8s-deploy-production.canary/job/master/build?delay=0sec"
    remediation_url: "https://TODO"

  tasks:
  - name: trigger jenkins pipeline
    vars:
      payload:  {"parameter": [{"name":"VERSION1", "value":"{{item.version1}}"}, {"name":"VERSION2", "value":"{{item.version2}}"}, {"name":"REMEDIATIONURL", "value":"{{remediation_url}}"}]}
    command:  curl -X POST {{jenkins_url}} --user admin:admin --data-urlencode json='{{payload | to_json}}'   
    loop:
      - version1: 100
        version2: 0
      - version1: 90
        version2: 10
      - version1: 50
        version2: 50
      - version1: 30
        version2: 70
      - version1: 0
        version2: 100
    loop_control:
      pause: 120

