---
- hosts: localhost
  tasks:

  - name: update deployment information
    uri:
      url: "{{dtdeploymentapiurl}}"
      method: POST
      body_format: json
      body: '{
            "eventType": "CUSTOM_DEPLOYMENT",
            "attachRules": {
              "tagRule" : [{
                  "meTypes" : ["SERVICE"],
                  "tags" : [ {
                    "context" : "CONTEXTLESS",
                    "key" : "Service",
                    "value" : "{{bookingservice_tag}}"            
                  }
                  ]
                }]
            },
            "deploymentName":"Disable microservice service",
            "deploymentVersion":"1.1",
            "deploymentProject":"Feature toggle",
            "source":"Ansible",
            "customProperties":{
                "CI Tool": "Ansible Tower",
                "Build Number": "123",
                "Git commit": "23422323233332"
            }
          }'
      return_content: yes
    register: deploymentresponse
    tags: 
      - featuretoggle-disable-microservice

