---
- hosts: localhost
  tasks:

  - name: update configuration for carts service
    uri:
      url: "{{dteventapiurl}}"
      method: POST
      body_format: json
      body: '{
            "eventType": "CUSTOM_CONFIGURATION",
            "attachRules": {
              "tagRule" : [{
                  "meTypes" : ["SERVICE"],
                  "tags" : [ {
                    "context" : "CONTEXTLESS",
                    "key" : "app",
                    "value" : "{{carts}}"            
                  }, {
                    "context" : "CONTEXTLESS",
                    "key" : "environment",
                    "value" : "{{dev}}" 
                  }
                  ]
                }]
            },
            "deploymentName":"Disable microservice service",
            "deploymentVersion":"1.1",
            "deploymentProject":"Feature toggle",
            "source":"Ansible",
            "customProperties":{
                "CI Tool": "Ansible Tower",
                "Build Number": "123",
                "Git commit": "23422323233332"
            }
          }'
      return_content: yes
    register: configurationresponse


