---
- hosts: localhost
  vars:
    dt_app: "carts"
    dt_env: "dev"

  tasks:
  - name: update response delay for {{dt_app}} service
    uri:
      url: "{{carts_delay_url}}/{{response_delay}}"
      method: GET
    tags:
      - response_delay_change

  - name: update error rate for {{dt_app}} service
    uri:
      url: "{{carts_error_url}}/{{error_rate}}"
      method: GET
    tags:
      - error_rate_change


  - name: update response configuration for {{dt_app}} service
    uri:
      url: "{{dteventapiurl}}"
      method: POST
      body_format: json
      body: '{
            "eventType": "CUSTOM_CONFIGURATION",
            "attachRules": {
              "tagRule" : [{
                  "meTypes" : ["SERVICE"],
                  "tags" : [ {
                    "context" : "CONTEXTLESS",
                    "key" : "app",
                    "value" : "{{dt_app}}"            
                  }, {
                    "context" : "CONTEXTLESS",
                    "key" : "environment",
                    "value" : "{{dt_env}}" 
                  }
                  ]
                }]
            },
            "description":"response delay set to {{response_delay}} ms",
            "source":"Ansible Tower",
            "configuration":"response delay",
            "customProperties": {
              "remediationAction": "{{remediation_action}}"
            }
          }'
      return_content: yes
    register: configurationresponse
    tags:
      - response_time_change


  - name: update erorr configuration for {{dt_app}} service
    uri:
      url: "{{dteventapiurl}}"
      method: POST
      body_format: json
      body: '{
            "eventType": "CUSTOM_CONFIGURATION",
            "attachRules": {
              "tagRule" : [{
                  "meTypes" : ["SERVICE"],
                  "tags" : [ {
                    "context" : "CONTEXTLESS",
                    "key" : "app",
                    "value" : "{{dt_app}}"            
                  }, {
                    "context" : "CONTEXTLESS",
                    "key" : "environment",
                    "value" : "{{dt_env}}" 
                  }
                  ]
                }]
            },
            "description":"error rate set to {{error_rate}} %",
            "source":"Ansible Tower",
            "configuration":"error rate",
            "customProperties": {
              "remediationAction": "{{remediation_action}}"
            }
          }'
      return_content: yes
    register: errorresponse
    tags:
      - error_rate_change


