---
- hosts: localhost
  tasks:

  - name: update response time for carts service
    uri:
      url: "{{carts_delay_url}}"
      method: GET

  - name: update error rate for carts service
    uri:
      url: "{{carts_error_url}}"
      method: GET

  - name: update configuration for carts service
    uri:
      url: "{{dteventapiurl}}"
      method: POST
      body_format: json
      body: '{
            "eventType": "CUSTOM_CONFIGURATION",
            "attachRules": {
              "tagRule" : [{
                  "meTypes" : ["SERVICE"],
                  "tags" : [ {
                    "context" : "CONTEXTLESS",
                    "key" : "app",
                    "value" : "carts"            
                  }, {
                    "context" : "CONTEXTLESS",
                    "key" : "environment",
                    "value" : "dev" 
                  }
                  ]
                }]
            },
            "description":"change settings",
            "source":"Ansible Tower",
            "configuration":"Response time \"tweak\"",
            "original":"zero"
          }'
      return_content: yes
    register: configurationresponse


